# Generated by Django 5.2.6 on 2025-09-04 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfumeFavoriteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='РљРѕСЂРёСЃС‚СѓРІР°С‡, СЏРєРёР№ РґРѕРґР°РІ Сѓ РІРёР±СЂР°РЅРµ', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'РЈР»СЋР±Р»РµРЅРёР№ РїР°СЂС„СѓРј',
                'verbose_name_plural': 'РЈР»СЋР±Р»РµРЅС– РїР°СЂС„СѓРјРё',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_fav_user_time'), models.Index(fields=['content_type', 'object_id'], name='idx_fav_target')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='uq_fav_user_target')],
            },
        ),
    ]
