# Generated by Django 5.2.9 on 2026-03-19 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fragrance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FragranceSimilaritySuggestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'РћС‡С–РєСѓС” РјРѕРґРµСЂР°С†С–С—'), ('approved', 'РЎС…РІР°Р»РµРЅРѕ'), ('rejected', 'Р’С–РґС…РёР»РµРЅРѕ РјРѕРґРµСЂР°С‚РѕСЂРѕРј'), ('hidden', 'РџСЂРёС…РѕРІР°РЅРѕ РІР»Р°СЃРЅРёРєРѕРј'), ('removed_by_moderator', 'Р’РёРґР°Р»РµРЅРѕ РјРѕРґРµСЂР°С‚РѕСЂРѕРј')], default='pending', max_length=40)),
                ('moderator_comment', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragrance_similarity_suggestions', to=settings.AUTH_USER_MODEL)),
                ('fragrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_suggestions', to='fragrance.fragrancemodel')),
                ('similar_fragrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to_suggestions', to='fragrance.fragrancemodel')),
            ],
            options={
                'db_table': 'fragrance_similarity_suggestion',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FragranceSimilarityVoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.SmallIntegerField(default=1)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='fragrance_ugc.fragrancesimilaritysuggestionmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragrance_similarity_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fragrance_similarity_vote',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserFragranceNoteSuggestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('top', 'Top'), ('heart', 'Heart'), ('base', 'Base')], default='top', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'РћС‡С–РєСѓС” РјРѕРґРµСЂР°С†С–С—'), ('approved', 'РЎС…РІР°Р»РµРЅРѕ'), ('rejected', 'Р’С–РґС…РёР»РµРЅРѕ РјРѕРґРµСЂР°С‚РѕСЂРѕРј'), ('hidden', 'РџСЂРёС…РѕРІР°РЅРѕ РІР»Р°СЃРЅРёРєРѕРј'), ('removed_by_moderator', 'Р’РёРґР°Р»РµРЅРѕ РјРѕРґРµСЂР°С‚РѕСЂРѕРј')], default='pending', max_length=40)),
                ('moderator_comment', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragrance_note_suggestions', to=settings.AUTH_USER_MODEL)),
                ('fragrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_suggestions', to='fragrance.fragrancemodel')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fragrance_suggestions', to='fragrance.notemodel')),
            ],
            options={
                'db_table': 'fragrance_note_suggestion',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserFragranceNoteVoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.SmallIntegerField(default=1)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='fragrance_ugc.userfragrancenotesuggestionmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragrance_note_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fragrance_note_vote',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FragranceAddRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(max_length=255)),
                ('fragrance_name', models.CharField(max_length=255)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('perfumers_text', models.CharField(blank=True, default='', max_length=500)),
                ('notes_text', models.TextField(blank=True, default='')),
                ('families_text', models.CharField(blank=True, default='', max_length=500)),
                ('links_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'РћС‡С–РєСѓС” РјРѕРґРµСЂР°С†С–С—'), ('approved', 'РЎС…РІР°Р»РµРЅРѕ'), ('rejected', 'Р’С–РґС…РёР»РµРЅРѕ РјРѕРґРµСЂР°С‚РѕСЂРѕРј'), ('hidden', 'РџСЂРёС…РѕРІР°РЅРѕ РІР»Р°СЃРЅРёРєРѕРј'), ('removed_by_moderator', 'Р’РёРґР°Р»РµРЅРѕ РјРѕРґРµСЂР°С‚РѕСЂРѕРј')], default='pending', max_length=32)),
                ('moderator_comment', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragrance_add_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fragrance_add_request',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_fr_addreq_status_time'), models.Index(fields=['created_by', 'created_at'], name='idx_fr_addreq_user_time'), models.Index(fields=['brand_name', 'fragrance_name'], name='idx_fr_addreq_brand_name')],
            },
        ),
        migrations.AddIndex(
            model_name='fragrancesimilaritysuggestionmodel',
            index=models.Index(fields=['fragrance', 'status', 'created_at'], name='idx_fr_sim_suggest_fr_st'),
        ),
        migrations.AddIndex(
            model_name='fragrancesimilaritysuggestionmodel',
            index=models.Index(fields=['created_by', 'created_at'], name='idx_fr_sim_suggest_user_time'),
        ),
        migrations.AddConstraint(
            model_name='fragrancesimilaritysuggestionmodel',
            constraint=models.UniqueConstraint(fields=('fragrance', 'similar_fragrance', 'created_by'), name='uq_fr_sim_suggest_user_once'),
        ),
        migrations.AddConstraint(
            model_name='fragrancesimilaritysuggestionmodel',
            constraint=models.CheckConstraint(condition=models.Q(('fragrance', models.F('similar_fragrance')), _negated=True), name='ck_fr_sim_not_self'),
        ),
        migrations.AddConstraint(
            model_name='fragrancesimilarityvotemodel',
            constraint=models.UniqueConstraint(fields=('suggestion', 'user'), name='uq_fr_sim_vote_once'),
        ),
        migrations.AddConstraint(
            model_name='fragrancesimilarityvotemodel',
            constraint=models.CheckConstraint(condition=models.Q(('value__in', [-1, 1])), name='ck_fr_sim_vote_value'),
        ),
        migrations.AddIndex(
            model_name='userfragrancenotesuggestionmodel',
            index=models.Index(fields=['fragrance', 'status', 'created_at'], name='idx_fr_note_suggest_fr_st'),
        ),
        migrations.AddIndex(
            model_name='userfragrancenotesuggestionmodel',
            index=models.Index(fields=['created_by', 'created_at'], name='idx_fr_note_suggest_user_time'),
        ),
        migrations.AddIndex(
            model_name='userfragrancenotesuggestionmodel',
            index=models.Index(fields=['fragrance', 'level', 'created_at'], name='idx_fr_note_suggest_fr_lvl'),
        ),
        migrations.AddConstraint(
            model_name='userfragrancenotesuggestionmodel',
            constraint=models.UniqueConstraint(fields=('fragrance', 'note', 'created_by', 'level'), name='uq_fr_note_suggest_user_once_per_level'),
        ),
        migrations.AddConstraint(
            model_name='userfragrancenotevotemodel',
            constraint=models.UniqueConstraint(fields=('suggestion', 'user'), name='uq_fr_note_vote_once'),
        ),
        migrations.AddConstraint(
            model_name='userfragrancenotevotemodel',
            constraint=models.CheckConstraint(condition=models.Q(('value__in', [-1, 1])), name='ck_fr_note_vote_value'),
        ),
    ]
