# Generated by Django 5.2.9 on 2026-03-31 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrance', '0002_alter_fragrancenoteofficialmodel_options_and_more'),
        ('fragrance_ugc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fragranceaddrequestmodel',
            name='created_fragrance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_add_requests', to='fragrance.fragrancemodel'),
        ),
        migrations.AddField(
            model_name='fragranceaddrequestmodel',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_fragrance_add_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
