# Generated by Django 5.2.13 on 2026-06-05 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fragrance', '0002_alter_fragrancenoteofficialmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TasteProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('about', models.TextField(blank=True, default='', max_length=700)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taste_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'taste_profile',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TastePerfumerPreferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attitude', models.CharField(choices=[('like', 'РџРѕРґРѕР±Р°С”С‚СЊСЃСЏ'), ('dislike', 'РќРµ РїРѕРґРѕР±Р°С”С‚СЊСЃСЏ')], max_length=20)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('perfumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taste_preferences', to='fragrance.perfumermodel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfumer_preferences', to='taste_profile.tasteprofilemodel')),
            ],
            options={
                'db_table': 'taste_perfumer_preference',
                'ordering': ['perfumer__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TasteNotePreferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attitude', models.CharField(choices=[('like', 'РџРѕРґРѕР±Р°С”С‚СЊСЃСЏ'), ('dislike', 'РќРµ РїРѕРґРѕР±Р°С”С‚СЊСЃСЏ')], max_length=20)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taste_preferences', to='fragrance.notemodel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_preferences', to='taste_profile.tasteprofilemodel')),
            ],
            options={
                'db_table': 'taste_note_preference',
                'ordering': ['note__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TasteFragranceMarkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mark', models.CharField(choices=[('looking_for', 'РЁСѓРєР°СЋ Р·Р°СЂР°Р·'), ('do_not_offer', 'РќРµ РїСЂРѕРїРѕРЅСѓРІР°С‚Рё')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'РќРёР·СЊРєРёР№'), ('normal', 'Р—РІРёС‡Р°Р№РЅРёР№'), ('high', 'Р’РёСЃРѕРєРёР№')], default='normal', max_length=20)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('fragrance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taste_marks', to='fragrance.fragrancemodel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragrance_marks', to='taste_profile.tasteprofilemodel')),
            ],
            options={
                'db_table': 'taste_fragrance_mark',
                'ordering': ['mark', '-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TasteFamilyPreferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attitude', models.CharField(choices=[('like', 'РџРѕРґРѕР±Р°С”С‚СЊСЃСЏ'), ('dislike', 'РќРµ РїРѕРґРѕР±Р°С”С‚СЊСЃСЏ')], max_length=20)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taste_preferences', to='fragrance.olfactoryfamilymodel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_preferences', to='taste_profile.tasteprofilemodel')),
            ],
            options={
                'db_table': 'taste_family_preference',
                'ordering': ['family__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TasteConcentrationPreferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concentration', models.CharField(choices=[('edc', 'Eau de Cologne'), ('edt', 'Eau de Toilette'), ('edp', 'Eau de Parfum'), ('parfum', 'Parfum'), ('extrait', 'Extrait de Parfum'), ('oil', 'Perfume Oil'), ('mist', 'Mist')], max_length=20)),
                ('attitude', models.CharField(choices=[('like', 'РџРѕРґРѕР±Р°С”С‚СЊСЃСЏ'), ('dislike', 'РќРµ РїРѕРґРѕР±Р°С”С‚СЊСЃСЏ')], max_length=20)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concentration_preferences', to='taste_profile.tasteprofilemodel')),
            ],
            options={
                'db_table': 'taste_concentration_preference',
                'ordering': ['concentration', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TasteBrandPreferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attitude', models.CharField(choices=[('like', 'РџРѕРґРѕР±Р°С”С‚СЊСЃСЏ'), ('dislike', 'РќРµ РїРѕРґРѕР±Р°С”С‚СЊСЃСЏ')], max_length=20)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taste_preferences', to='fragrance.brandmodel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_preferences', to='taste_profile.tasteprofilemodel')),
            ],
            options={
                'db_table': 'taste_brand_preference',
                'ordering': ['brand__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TasteSeasonPreferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.CharField(choices=[('spring', 'Р’РµСЃРЅР°'), ('summer', 'Р›С–С‚Рѕ'), ('autumn', 'РћСЃС–РЅСЊ'), ('winter', 'Р—РёРјР°'), ('all_season', 'Р‘СѓРґСЊ-СЏРєРёР№ СЃРµР·РѕРЅ')], max_length=20)),
                ('attitude', models.CharField(choices=[('like', 'РџРѕРґРѕР±Р°С”С‚СЊСЃСЏ'), ('dislike', 'РќРµ РїРѕРґРѕР±Р°С”С‚СЊСЃСЏ')], max_length=20)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_preferences', to='taste_profile.tasteprofilemodel')),
            ],
            options={
                'db_table': 'taste_season_preference',
                'ordering': ['season', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='tasteprofilemodel',
            index=models.Index(fields=['user'], name='idx_taste_profile_user'),
        ),
        migrations.AddIndex(
            model_name='tasteprofilemodel',
            index=models.Index(fields=['is_public'], name='idx_taste_profile_public'),
        ),
        migrations.AddIndex(
            model_name='tasteperfumerpreferencemodel',
            index=models.Index(fields=['profile', 'attitude'], name='idx_taste_perf_prof_att'),
        ),
        migrations.AddIndex(
            model_name='tasteperfumerpreferencemodel',
            index=models.Index(fields=['perfumer', 'attitude'], name='idx_taste_perf_att'),
        ),
        migrations.AddConstraint(
            model_name='tasteperfumerpreferencemodel',
            constraint=models.UniqueConstraint(fields=('profile', 'perfumer'), name='uq_taste_profile_perfumer'),
        ),
        migrations.AddIndex(
            model_name='tastenotepreferencemodel',
            index=models.Index(fields=['profile', 'attitude'], name='idx_taste_note_prof_att'),
        ),
        migrations.AddIndex(
            model_name='tastenotepreferencemodel',
            index=models.Index(fields=['note', 'attitude'], name='idx_taste_note_att'),
        ),
        migrations.AddConstraint(
            model_name='tastenotepreferencemodel',
            constraint=models.UniqueConstraint(fields=('profile', 'note'), name='uq_taste_profile_note'),
        ),
        migrations.AddIndex(
            model_name='tastefragrancemarkmodel',
            index=models.Index(fields=['profile', 'mark', '-updated_at'], name='idx_taste_fr_prof_mark_upd'),
        ),
        migrations.AddIndex(
            model_name='tastefragrancemarkmodel',
            index=models.Index(fields=['fragrance', 'mark'], name='idx_taste_fragrance_mark'),
        ),
        migrations.AddIndex(
            model_name='tastefragrancemarkmodel',
            index=models.Index(fields=['profile', 'priority'], name='idx_taste_fr_prof_priority'),
        ),
        migrations.AddConstraint(
            model_name='tastefragrancemarkmodel',
            constraint=models.UniqueConstraint(fields=('profile', 'fragrance'), name='uq_taste_profile_fragrance'),
        ),
        migrations.AddIndex(
            model_name='tastefamilypreferencemodel',
            index=models.Index(fields=['profile', 'attitude'], name='idx_taste_family_prof_att'),
        ),
        migrations.AddIndex(
            model_name='tastefamilypreferencemodel',
            index=models.Index(fields=['family', 'attitude'], name='idx_taste_family_att'),
        ),
        migrations.AddConstraint(
            model_name='tastefamilypreferencemodel',
            constraint=models.UniqueConstraint(fields=('profile', 'family'), name='uq_taste_profile_family'),
        ),
        migrations.AddIndex(
            model_name='tasteconcentrationpreferencemodel',
            index=models.Index(fields=['profile', 'attitude'], name='idx_taste_conc_prof_att'),
        ),
        migrations.AddIndex(
            model_name='tasteconcentrationpreferencemodel',
            index=models.Index(fields=['concentration', 'attitude'], name='idx_taste_conc_att'),
        ),
        migrations.AddConstraint(
            model_name='tasteconcentrationpreferencemodel',
            constraint=models.UniqueConstraint(fields=('profile', 'concentration'), name='uq_taste_profile_concentration'),
        ),
        migrations.AddIndex(
            model_name='tastebrandpreferencemodel',
            index=models.Index(fields=['profile', 'attitude'], name='idx_taste_brand_prof_att'),
        ),
        migrations.AddIndex(
            model_name='tastebrandpreferencemodel',
            index=models.Index(fields=['brand', 'attitude'], name='idx_taste_brand_att'),
        ),
        migrations.AddConstraint(
            model_name='tastebrandpreferencemodel',
            constraint=models.UniqueConstraint(fields=('profile', 'brand'), name='uq_taste_profile_brand'),
        ),
        migrations.AddIndex(
            model_name='tasteseasonpreferencemodel',
            index=models.Index(fields=['profile', 'attitude'], name='idx_taste_season_prof_att'),
        ),
        migrations.AddIndex(
            model_name='tasteseasonpreferencemodel',
            index=models.Index(fields=['season', 'attitude'], name='idx_taste_season_att'),
        ),
        migrations.AddConstraint(
            model_name='tasteseasonpreferencemodel',
            constraint=models.UniqueConstraint(fields=('profile', 'season'), name='uq_taste_profile_season'),
        ),
    ]
