# Generated by Django 5.2.13 on 2026-06-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taste_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tastefragrancemarkmodel',
            name='mark',
            field=models.CharField(choices=[('looking_for', 'Р—Р°СЂР°Р· С€СѓРєР°СЋ'), ('do_not_offer', 'РќРµ РїСЂРѕРїРѕРЅСѓРІР°С‚Рё')], max_length=30),
        ),
    ]
