from django.db import models


class RegionChoices(models.TextChoices):
    KYIV_CITY = 'kyiv_city', 'РљРёС—РІ'
    VINNYTSIA = 'vinnytsia', 'Р’С–РЅРЅРёС†СЊРєР°'
    VOLYN = 'volyn', 'Р’РѕР»РёРЅСЃСЊРєР°'
    DNIPROPETROVSK = 'dnipropetrovsk', 'Р”РЅС–РїСЂРѕРїРµС‚СЂРѕРІСЃСЊРєР°'
    DONETSK = 'donetsk', 'Р”РѕРЅРµС†СЊРєР°'
    ZHYTOMYR = 'zhytomyr', 'Р–РёС‚РѕРјРёСЂСЃСЊРєР°'
    ZAKARPATTIA = 'zakarpattia', 'Р—Р°РєР°СЂРїР°С‚СЃСЊРєР°'
    ZAPORIZHZHIA = 'zaporizhzhia', 'Р—Р°РїРѕСЂС–Р·СЊРєР°'
    IVANO_FRANKIVSK = 'ivano_frankivsk', 'Р†РІР°РЅРѕ-Р¤СЂР°РЅРєС–РІСЃСЊРєР°'
    KYIV_REGION = 'kyiv_region', 'РљРёС—РІСЃСЊРєР°'
    KIROVOHRAD = 'kirovohrad', 'РљС–СЂРѕРІРѕРіСЂР°РґСЃСЊРєР°'
    LUHANSK = 'luhansk', 'Р›СѓРіР°РЅСЃСЊРєР°'
    LVIV = 'lviv', 'Р›СЊРІС–РІСЃСЊРєР°'
    MYKOLAIV = 'mykolaiv', 'РњРёРєРѕР»Р°С—РІСЃСЊРєР°'
    ODESA = 'odesa', 'РћРґРµСЃСЊРєР°'
    POLTAVA = 'poltava', 'РџРѕР»С‚Р°РІСЃСЊРєР°'
    RIVNE = 'rivne', 'Р С–РІРЅРµРЅСЃСЊРєР°'
    SUMY = 'sumy', 'РЎСѓРјСЃСЊРєР°'
    TERNOPIL = 'ternopil', 'РўРµСЂРЅРѕРїС–Р»СЊСЃСЊРєР°'
    KHARKIV = 'kharkiv', 'РҐР°СЂРєС–РІСЃСЊРєР°'
    KHERSON = 'kherson', 'РҐРµСЂСЃРѕРЅСЃСЊРєР°'
    KHMELNYTSKYI = 'khmelnytskyi', 'РҐРјРµР»СЊРЅРёС†СЊРєР°'
    CHERKASY = 'cherkasy', 'Р§РµСЂРєР°СЃСЊРєР°'
    CHERNIVTSI = 'chernivtsi', 'Р§РµСЂРЅС–РІРµС†СЊРєР°'
    CHERNIHIV = 'chernihiv', 'Р§РµСЂРЅС–РіС–РІСЃСЊРєР°'
    CRIMEA = 'crimea', 'РђР  РљСЂРёРј'
    OTHER = 'other', 'Р†РЅС€Рµ'
