# Generated by Django 5.2.6 on 2025-09-04 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_block_no_self_block_follow_no_self_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['blocked'], name='idx_block_blocked'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['blocker'], name='idx_block_blocker'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['followee'], name='idx_follow_followee'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower'], name='idx_follow_follower'),
        ),
    ]
