# Generated by Django 5.2.9 on 2026-02-15 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('social', '0003_block_idx_block_blocked_block_idx_block_blocker_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Block',
            new_name='BlockModel',
        ),
        migrations.RenameModel(
            old_name='Follow',
            new_name='FollowModel',
        ),
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_subscription',
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_sub_user_time'), models.Index(fields=['content_type', 'object_id'], name='idx_sub_target')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='uq_sub_user_target')],
            },
        ),
    ]
