# Generated by Django 5.2.4 on 2025-08-29 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0002_rename_notification_notificationmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificationmodel',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='idx_notif_user_read_time'),
        ),
        migrations.AddIndex(
            model_name='notificationmodel',
            index=models.Index(fields=['actor_ct', 'actor_id'], name='idx_notif_actor'),
        ),
        migrations.AddIndex(
            model_name='notificationmodel',
            index=models.Index(fields=['target_ct', 'target_id'], name='idx_notif_target'),
        ),
    ]
