# Generated by Django 5.2.6 on 2025-09-04 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0003_notificationmodel_idx_notif_user_read_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificationmodel',
            index=models.Index(fields=['user', 'created_at'], name='idx_notif_user_time'),
        ),
        migrations.AddIndex(
            model_name='notificationmodel',
            index=models.Index(fields=['user', 'is_read'], name='idx_notif_user_read'),
        ),
    ]
