# Generated by Django 5.2.13 on 2026-04-30 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_activityeventmodel_verb_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0004_notificationmodel_idx_notif_user_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='activity_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='activity.activityeventmodel'),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notificationmodel',
            index=models.Index(fields=['verb', 'created_at'], name='idx_notif_verb_created'),
        ),
        migrations.AddIndex(
            model_name='notificationmodel',
            index=models.Index(fields=['activity_event'], name='idx_notif_activity_event'),
        ),
        migrations.AddConstraint(
            model_name='notificationmodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_ct__isnull', True), ('target_id__isnull', True)), models.Q(('target_ct__isnull', False), ('target_id__isnull', False)), _connector='OR'), name='notification_target_all_or_none'),
        ),
    ]
