# Generated by Django 5.2.4 on 2025-07-24 13:12

import apps.users.managers
import core.common_services.file_service
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('account_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=10)),
                ('is_upgrade_to_premium', models.BooleanField(default=False)),
                ('last_logout', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=55, unique=True)),
                ('region', models.CharField(choices=[('kyiv_city', 'РљРёС—РІ'), ('vinnytsia', 'Р’С–РЅРЅРёС†СЊРєР°'), ('volyn', 'Р’РѕР»РёРЅСЃСЊРєР°'), ('dnipropetrovsk', 'Р”РЅС–РїСЂРѕРїРµС‚СЂРѕРІСЃСЊРєР°'), ('donetsk', 'Р”РѕРЅРµС†СЊРєР°'), ('zhytomyr', 'Р–РёС‚РѕРјРёСЂСЃСЊРєР°'), ('zakarpattia', 'Р—Р°РєР°СЂРїР°С‚СЃСЊРєР°'), ('zaporizhzhia', 'Р—Р°РїРѕСЂС–Р·СЊРєР°'), ('ivano_frankivsk', 'Р†РІР°РЅРѕ-Р¤СЂР°РЅРєС–РІСЃСЊРєР°'), ('kyiv_region', 'РљРёС—РІСЃСЊРєР°'), ('kirovohrad', 'РљС–СЂРѕРІРѕРіСЂР°РґСЃСЊРєР°'), ('luhansk', 'Р›СѓРіР°РЅСЃСЊРєР°'), ('lviv', 'Р›СЊРІС–РІСЃСЊРєР°'), ('mykolaiv', 'РњРёРєРѕР»Р°С—РІСЃСЊРєР°'), ('odesa', 'РћРґРµСЃСЊРєР°'), ('poltava', 'РџРѕР»С‚Р°РІСЃСЊРєР°'), ('rivne', 'Р С–РІРЅРµРЅСЃСЊРєР°'), ('sumy', 'РЎСѓРјСЃСЊРєР°'), ('ternopil', 'РўРµСЂРЅРѕРїС–Р»СЊСЃСЊРєР°'), ('kharkiv', 'РҐР°СЂРєС–РІСЃСЊРєР°'), ('kherson', 'РҐРµСЂСЃРѕРЅСЃСЊРєР°'), ('khmelnytskyi', 'РҐРјРµР»СЊРЅРёС†СЊРєР°'), ('cherkasy', 'Р§РµСЂРєР°СЃСЊРєР°'), ('chernivtsi', 'Р§РµСЂРЅС–РІРµС†СЊРєР°'), ('chernihiv', 'Р§РµСЂРЅС–РіС–РІСЃСЊРєР°'), ('crimea', 'РђР  РљСЂРёРј'), ('other', 'Р†РЅС€Рµ')], default='other', max_length=30)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=core.common_services.file_service.upload_avatar)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
                'ordering': ['id'],
            },
        ),
    ]
