# Generated by Django 5.2.4 on 2025-07-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(default='Anonymous', max_length=25),
            preserve_default=False,
        ),
    ]
