# Generated by Django 5.2.4 on 2025-08-17 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_socialaccountmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('notifications_unread_count', models.PositiveIntegerField(default=0)),
                ('last_notifications_read_at', models.DateTimeField(blank=True, null=True)),
                ('messages_unread_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_stats',
            },
        ),
    ]
