# Generated by Django 5.2.4 on 2025-08-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userstatsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='about_me',
            field=models.TextField(blank=True, max_length=355, null=True),
        ),
    ]
