# Generated by Django 5.2.6 on 2025-09-04 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profilemodel_about_me'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialaccountmodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialaccountmodel',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddIndex(
            model_name='socialaccountmodel',
            index=models.Index(fields=['user', 'provider'], name='idx_social_user_provider'),
        ),
        migrations.AddIndex(
            model_name='socialaccountmodel',
            index=models.Index(fields=['provider', 'provider_user_id'], name='idx_social_provider_extid'),
        ),
        migrations.AddConstraint(
            model_name='socialaccountmodel',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='uniq_social_provider_user'),
        ),
    ]
