# Generated by Django 5.2.6 on 2025-10-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_socialaccountmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profilemodel',
            table='users_profile',
        ),
    ]
