# Generated by Django 5.2.7 on 2025-12-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profilemodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
