# Generated by Django 5.2.9 on 2025-12-28 11:38

from django.db import migrations, models


def forwards_fill_display_name_ci(apps, schema_editor):
    Profile = apps.get_model("users", "ProfileModel")

    # Р—Р°РїРѕР»РЅСЏРµРј display_name_ci = lower(trim(remove spaces)) РѕС‚ display_name
    # (РґРѕР»Р¶РЅРѕ СЃРѕРІРїР°РґР°С‚СЊ СЃ С‚РІРѕРёРј display_name_ci(normalize_display_name(...)) )
    for p in Profile.objects.all().only("id", "display_name"):
        dn = (p.display_name or "").strip()
        dn = "".join(dn.split())  # СѓР±СЂР°С‚СЊ РїСЂРѕР±РµР»С‹/РІСЃРµ whitespace
        p.display_name_ci = dn.lower()
        p.save(update_fields=["display_name_ci"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_usermodel_email_verified"),
    ]

    operations = [
        # 1) Р”РѕР±Р°РІР»СЏРµРј РїРѕР»Рµ РњРЇР“РљРћ: nullable Рё Р±РµР· unique
        migrations.AddField(
            model_name="profilemodel",
            name="display_name_ci",
            field=models.CharField(
                max_length=55,
                null=True,
                blank=True,
                db_index=True,
                editable=False,
            ),
        ),

        # 2) Р—Р°РїРѕР»РЅСЏРµРј СЃСѓС‰РµСЃС‚РІСѓСЋС‰РёРµ СЃС‚СЂРѕРєРё
        migrations.RunPython(forwards_fill_display_name_ci, migrations.RunPython.noop),

        # 3) РЈР¶РёРјР°РµРј РїРѕР»Рµ РґРѕ РЅСѓР¶РЅРѕРіРѕ РІРёРґР°: NOT NULL + UNIQUE
        migrations.AlterField(
            model_name="profilemodel",
            name="display_name_ci",
            field=models.CharField(
                max_length=55,
                null=False,
                db_index=True,
                editable=False,
                unique=True,
            ),
        ),
    ]
