# Generated by Django 5.2.9 on 2026-01-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profilemodel_display_name_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_seller',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
