# Generated by Django 5.2.9 on 2026-01-26 16:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_usermodel_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatsmodel',
            name='started_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_suspensions_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_reason', models.CharField(blank=True, default='', max_length=32)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensions_made', to=settings.AUTH_USER_MODEL)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unsuspensions_made', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['target', '-started_at'], name='users_users_target__5c7ff1_idx'), models.Index(fields=['target', 'ended_at'], name='users_users_target__987bd7_idx'), models.Index(fields=['until'], name='users_users_until_01ce01_idx')],
            },
        ),
    ]
