# Generated by Django 5.2.9 on 2026-02-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userstatsmodel_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatsmodel',
            name='forum_comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='forum_topics_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='likes_given_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsmodel',
            name='likes_received_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
