# Generated by Django 5.2.13 on 2026-05-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0014_usermodel_role_suspended_indefinitely'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersuspension',
            new_name='idx_susp_target_started',
            old_name='users_users_target__5c7ff1_idx',
        ),
        migrations.RenameIndex(
            model_name='usersuspension',
            new_name='idx_susp_target_ended',
            old_name='users_users_target__987bd7_idx',
        ),
        migrations.RenameIndex(
            model_name='usersuspension',
            new_name='idx_susp_until',
            old_name='users_users_until_01ce01_idx',
        ),
        migrations.AlterField(
            model_name='socialaccountmodel',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Email, РѕС‚СЂРёРјР°РЅРёР№ РІС–Рґ OAuth provider. Р”Р¶РµСЂРµР»Рѕ С–СЃС‚РёРЅРё вЂ” UserModel.email.', max_length=254),
        ),
        migrations.AlterField(
            model_name='socialaccountmodel',
            name='provider',
            field=models.CharField(choices=[('google', 'Google')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='usermodel',
            index=models.Index(fields=['suspended_indefinitely'], name='idx_user_susp_indef'),
        ),
        migrations.AddIndex(
            model_name='usermodel',
            index=models.Index(fields=['role', 'is_active'], name='idx_user_role_active'),
        ),
        migrations.AlterModelTable(
            name='usersuspension',
            table='user_suspension',
        ),
    ]
