# Generated by Django 5.2.13 on 2026-06-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_sanitize_email_derived_display_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='account_type',
            field=models.CharField(choices=[('basic', 'Р‘Р°Р·РѕРІРёР№'), ('premium', 'РџСЂРµРјС–СѓРј')], default='basic', max_length=10),
        ),
    ]
