# Generated by Django 5.2.13 on 2026-06-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Р§РµСЂРЅРµС‚РєР°'), ('pending', 'РќР° РјРѕРґРµСЂР°С†С–С—'), ('published', 'РћРїСѓР±Р»С–РєРѕРІР°РЅРѕ'), ('rejected', 'Р’С–РґС…РёР»РµРЅРѕ')], default='draft', max_length=20),
        ),
    ]
