# Generated by Django 5.2.4 on 2025-08-18 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(choices=[('chanel', 'Chanel'), ('dior', 'Dior'), ('guerlain', 'Guerlain'), ('armani', 'Armani'), ('other', 'Other / Unknown')], default='other', max_length=50)),
                ('perfume_name', models.CharField(choices=[('n5', 'Chanel No. 5'), ('coco', 'Coco Mademoiselle'), ('sauvage', 'Dior Sauvage'), ('dior_homme', 'Dior Homme'), ('other', 'Other / Unknown')], default='other', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wardrobe_item',
                'ordering': ['brand', 'perfume_name'],
            },
        ),
    ]
