# Generated by Django 5.2.4 on 2025-08-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeitem',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='status',
            field=models.CharField(choices=[('own', 'Own'), ('want', 'Want'), ('had', 'Had'), ('sample', 'Sample'), ('favorite', 'Favorite')], default='own', max_length=20),
        ),
    ]
