# Generated by Django 5.2.6 on 2025-09-04 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_wardrobeitem_is_private_wardrobeitem_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WardrobeItem',
            new_name='WardrobeItemModel',
        ),
        migrations.AddIndex(
            model_name='wardrobeitemmodel',
            index=models.Index(fields=['user', '-updated_at'], name='wardrobe_it_user_id_3e7972_idx'),
        ),
        migrations.AddIndex(
            model_name='wardrobeitemmodel',
            index=models.Index(fields=['user', 'is_private', '-updated_at'], name='wardrobe_it_user_id_23b3ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='wardrobeitemmodel',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 10)), _connector='OR'), name='wardrobe_rating_between_1_10_or_null'),
        ),
        migrations.AddConstraint(
            model_name='wardrobeitemmodel',
            constraint=models.UniqueConstraint(fields=('user', 'brand', 'perfume_name', 'status'), name='ux_wardrobe_user_brand_name_status'),
        ),
    ]
