# Generated by Django 5.2.13 on 2026-05-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0003_rename_wardrobeitem_wardrobeitemmodel_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wardrobeitemmodel',
            new_name='idx_wardrobe_user_updated',
            old_name='wardrobe_it_user_id_3e7972_idx',
        ),
        migrations.RenameIndex(
            model_name='wardrobeitemmodel',
            new_name='idx_wrd_user_priv_upd',
            old_name='wardrobe_it_user_id_23b3ae_idx',
        ),
    ]
