# Generated by Django 5.2.13 on 2026-05-15

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


BRAND_LABELS = {
    "chanel": "Chanel",
    "dior": "Dior",
    "guerlain": "Guerlain",
    "armani": "Armani",
    "other": "Other / Unknown",
}

PERFUME_LABELS = {
    "n5": "Chanel No. 5",
    "coco": "Coco Mademoiselle",
    "sauvage": "Dior Sauvage",
    "dior_homme": "Dior Homme",
    "other": "Other / Unknown",
}


def unique_slug(model_cls, value):
    base = slugify((value or "").strip(), allow_unicode=True)[:240] or "item"
    slug = base
    idx = 2

    while model_cls.objects.filter(slug=slug).exists():
        suffix = f"-{idx}"
        slug = f"{base[:255 - len(suffix)]}{suffix}"
        idx += 1

    return slug


def migrate_legacy_wardrobe_items(apps, schema_editor):
    WardrobeItem = apps.get_model("wardrobe", "WardrobeItemModel")
    Brand = apps.get_model("fragrance", "BrandModel")
    Fragrance = apps.get_model("fragrance", "FragranceModel")

    for item in WardrobeItem.objects.filter(fragrance__isnull=True):
        brand_name = BRAND_LABELS.get(item.brand, item.brand or BRAND_LABELS["other"])
        perfume_name = PERFUME_LABELS.get(
            item.perfume_name,
            item.perfume_name or PERFUME_LABELS["other"],
        )

        brand, _ = Brand.objects.get_or_create(
            name=brand_name,
            defaults={"slug": unique_slug(Brand, brand_name)},
        )
        fragrance, _ = Fragrance.objects.get_or_create(
            brand=brand,
            name=perfume_name,
            defaults={"slug": unique_slug(Fragrance, f"{brand_name} {perfume_name}")},
        )

        item.fragrance = fragrance
        item.save(update_fields=["fragrance"])


class Migration(migrations.Migration):

    dependencies = [
        ("fragrance", "0002_alter_fragrancenoteofficialmodel_options_and_more"),
        (
            "wardrobe",
            "0004_rename_wardrobe_it_user_id_3e7972_idx_idx_wardrobe_user_updated_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wardrobeitemmodel",
            options={
                "ordering": ["fragrance__brand__name", "fragrance__name", "status"],
            },
        ),
        migrations.AddField(
            model_name="wardrobeitemmodel",
            name="fragrance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wardrobe_items",
                to="fragrance.fragrancemodel",
            ),
        ),
        migrations.RunPython(
            migrate_legacy_wardrobe_items,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="wardrobeitemmodel",
            name="fragrance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wardrobe_items",
                to="fragrance.fragrancemodel",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="wardrobeitemmodel",
            name="ux_wardrobe_user_brand_name_status",
        ),
        migrations.RemoveField(
            model_name="wardrobeitemmodel",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="wardrobeitemmodel",
            name="perfume_name",
        ),
        migrations.AddIndex(
            model_name="wardrobeitemmodel",
            index=models.Index(
                fields=["user", "fragrance", "status"],
                name="idx_wrd_user_fr_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="wardrobeitemmodel",
            constraint=models.UniqueConstraint(
                fields=("user", "fragrance", "status"),
                name="ux_wardrobe_user_fragrance_status",
            ),
        ),
    ]
