# Generated by Django 5.2.13 on 2026-06-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0005_migrate_items_to_fragrance_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobeitemmodel',
            name='status',
            field=models.CharField(choices=[('own', 'РњР°СЋ'), ('want', 'РҐРѕС‡Сѓ'), ('had', 'Р‘СѓРІ СЂР°РЅС–С€Рµ'), ('sample', 'РњР°СЋ РїСЂРѕР±РЅРёРє'), ('favorite', 'РЈР»СЋР±Р»РµРЅРёР№')], default='own', max_length=20),
        ),
    ]
