# Generated by Django 5.2.4 on 2025-08-25 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activityeventmodel',
            name='activity_ev_actor_i_841e79_idx',
        ),
        migrations.RemoveIndex(
            model_name='activityeventmodel',
            name='activity_ev_created_e69fcc_idx',
        ),
        migrations.RemoveIndex(
            model_name='activityeventmodel',
            name='activity_ev_target__931a4c_idx',
        ),
        migrations.RemoveField(
            model_name='activityeventmodel',
            name='target_content_type',
        ),
        migrations.RemoveField(
            model_name='activityeventmodel',
            name='target_object_id',
        ),
        migrations.AddIndex(
            model_name='activityeventmodel',
            index=models.Index(fields=['actor', 'created_at'], name='idx_activity_actor_created'),
        ),
        migrations.AddIndex(
            model_name='activityeventmodel',
            index=models.Index(fields=['created_at'], name='idx_activity_created'),
        ),
        migrations.AddIndex(
            model_name='activityeventmodel',
            index=models.Index(fields=['target_app', 'target_model', 'target_id'], name='idx_activity_target_triplet'),
        ),
    ]
