# Generated by Django 5.2.4 on 2025-08-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_remove_activityeventmodel_activity_ev_actor_i_841e79_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityeventmodel',
            name='verb',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('commented', 'Commented')], max_length=120),
        ),
    ]
