# Generated by Django 5.2.6 on 2025-09-04 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activityeventmodel_verb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activityeventmodel',
            index=models.Index(fields=['is_private', 'created_at'], name='idx_activity_public_created'),
        ),
        migrations.AddIndex(
            model_name='activityeventmodel',
            index=models.Index(fields=['target_app', 'target_model', 'target_id', 'created_at'], name='idx_activity_target_created'),
        ),
        migrations.AddConstraint(
            model_name='activityeventmodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_app', ''), ('target_model', ''), ('target_id__isnull', True)), models.Q(models.Q(('target_app', ''), _negated=True), models.Q(('target_model', ''), _negated=True), ('target_id__isnull', False)), _connector='OR'), name='activity_target_all_or_none'),
        ),
    ]
