# Generated by Django 5.2.13 on 2026-04-30 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_activityeventmodel_idx_activity_public_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityeventmodel',
            name='verb',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('commented', 'Commented'), ('liked', 'Liked'), ('favorited', 'Favorited'), ('exchange_created', 'Exchange created'), ('exchange_updated', 'Exchange updated')], max_length=120),
        ),
        migrations.AddIndex(
            model_name='activityeventmodel',
            index=models.Index(fields=['verb', 'created_at'], name='idx_activity_verb_created'),
        ),
    ]
