# Generated by Django 5.2.13 on 2026-05-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_activityeventmodel_verb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityeventmodel',
            name='verb',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('commented', 'Commented'), ('liked', 'Liked'), ('favorited', 'Favorited'), ('followed_user', 'Followed user'), ('exchange_created', 'Exchange created'), ('exchange_updated', 'Exchange updated')], max_length=120),
        ),
    ]
