# Generated by Django 5.2.13 on 2026-06-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_alter_activityeventmodel_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityeventmodel',
            name='verb',
            field=models.CharField(choices=[('created', 'РЎС‚РІРѕСЂРµРЅРѕ'), ('updated', 'РћРЅРѕРІР»РµРЅРѕ'), ('deleted', 'Р’РёРґР°Р»РµРЅРѕ'), ('commented', 'РџСЂРѕРєРѕРјРµРЅС‚РѕРІР°РЅРѕ'), ('liked', 'Р’РїРѕРґРѕР±Р°РЅРѕ'), ('favorited', 'Р”РѕРґР°РЅРѕ РґРѕ РѕР±СЂР°РЅРѕРіРѕ'), ('followed_user', 'РџС–РґРїРёСЃРєР° РЅР° РєРѕСЂРёСЃС‚СѓРІР°С‡Р°'), ('exchange_created', 'РћР±РјС–РЅ СЃС‚РІРѕСЂРµРЅРѕ'), ('exchange_updated', 'РћР±РјС–РЅ РѕРЅРѕРІР»РµРЅРѕ'), ('review_published', 'Р’С–РґРіСѓРє РѕРїСѓР±Р»С–РєРѕРІР°РЅРѕ')], max_length=120),
        ),
    ]
