# Generated by Django 5.2.15 on 2026-07-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_clean_notification_text_from_activity_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityeventmodel',
            name='verb',
            field=models.CharField(choices=[('user.followed', 'User followed'), ('wardrobe.item_added', 'Wardrobe item added'), ('exchange.created', 'Exchange created'), ('exchange.accepted', 'Exchange accepted'), ('exchange.rejected', 'Exchange rejected'), ('forum.topic_created', 'Forum topic created'), ('forum.comment_created', 'Forum comment created'), ('article.created', 'Article created')], max_length=120),
        ),
    ]
