# Generated by Django 5.2.9 on 2026-02-15 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'tag',
                'ordering': ('code',),
                'indexes': [models.Index(fields=['code'], name='idx_tag_code')],
            },
        ),
        migrations.CreateModel(
            name='TaggedItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tags.tagmodel')),
            ],
            options={
                'db_table': 'tagged_item',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='idx_tagged_target'), models.Index(fields=['tag', 'created_at'], name='idx_tagged_tag_time')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'tag'), name='uq_tagged_item_target_tag')],
            },
        ),
    ]
