# Generated by Django 5.2.13 on 2026-05-25 10:27

import core.validators.tags_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditemmodel',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='code',
            field=models.CharField(max_length=32, unique=True, validators=[core.validators.tags_validators.validate_tag_code]),
        ),
    ]
