# Generated by Django 5.2.9 on 2026-03-19 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('country', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'db_table': 'fragrance_brand',
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['name'], name='idx_fr_brand_name'), models.Index(fields=['slug'], name='idx_fr_brand_slug')],
            },
        ),
        migrations.CreateModel(
            name='FragranceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fragrances', to='fragrance.brandmodel')),
            ],
            options={
                'db_table': 'fragrance',
                'ordering': ['brand__name', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FragranceFamilyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fragrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fragrance.fragrancemodel')),
            ],
            options={
                'db_table': 'fragrance_family_link',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'fragrance_note',
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['name'], name='idx_fr_note_name'), models.Index(fields=['slug'], name='idx_fr_note_slug')],
            },
        ),
        migrations.CreateModel(
            name='FragranceNoteOfficialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('top', 'Top'), ('heart', 'Heart'), ('base', 'Base')], default='top', max_length=20)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('fragrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fragrance.fragrancemodel')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fragrance.notemodel')),
            ],
            options={
                'db_table': 'fragrance_note_official',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='fragrancemodel',
            name='notes_official',
            field=models.ManyToManyField(blank=True, related_name='fragrances_official', through='fragrance.FragranceNoteOfficialModel', to='fragrance.notemodel'),
        ),
        migrations.CreateModel(
            name='OlfactoryFamilyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'fragrance_family',
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['name'], name='idx_fr_family_name'), models.Index(fields=['slug'], name='idx_fr_family_slug')],
            },
        ),
        migrations.AddField(
            model_name='fragrancemodel',
            name='families',
            field=models.ManyToManyField(blank=True, related_name='fragrances', through='fragrance.FragranceFamilyModel', to='fragrance.olfactoryfamilymodel'),
        ),
        migrations.AddField(
            model_name='fragrancefamilymodel',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fragrance.olfactoryfamilymodel'),
        ),
        migrations.CreateModel(
            name='PerfumerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'fragrance_perfumer',
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['name'], name='idx_fr_perfumer_name')],
            },
        ),
        migrations.CreateModel(
            name='FragrancePerfumerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fragrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fragrance.fragrancemodel')),
                ('perfumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fragrance.perfumermodel')),
            ],
            options={
                'db_table': 'fragrance_perfumer_link',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='fragrancemodel',
            name='perfumers',
            field=models.ManyToManyField(blank=True, related_name='fragrances', through='fragrance.FragrancePerfumerModel', to='fragrance.perfumermodel'),
        ),
        migrations.AddIndex(
            model_name='fragrancenoteofficialmodel',
            index=models.Index(fields=['fragrance', 'position'], name='idx_fr_note_off_pos'),
        ),
        migrations.AddIndex(
            model_name='fragrancenoteofficialmodel',
            index=models.Index(fields=['note'], name='idx_fr_note_off_note'),
        ),
        migrations.AddConstraint(
            model_name='fragrancenoteofficialmodel',
            constraint=models.UniqueConstraint(fields=('fragrance', 'note'), name='uq_fr_note_official'),
        ),
        migrations.AddIndex(
            model_name='fragrancefamilymodel',
            index=models.Index(fields=['fragrance'], name='idx_fr_family_link_fr'),
        ),
        migrations.AddIndex(
            model_name='fragrancefamilymodel',
            index=models.Index(fields=['family'], name='idx_fr_family_link_family'),
        ),
        migrations.AddConstraint(
            model_name='fragrancefamilymodel',
            constraint=models.UniqueConstraint(fields=('fragrance', 'family'), name='uq_fr_family_link'),
        ),
        migrations.AddIndex(
            model_name='fragranceperfumermodel',
            index=models.Index(fields=['fragrance'], name='idx_fr_perf_link_fr'),
        ),
        migrations.AddIndex(
            model_name='fragranceperfumermodel',
            index=models.Index(fields=['perfumer'], name='idx_fr_perf_link_perf'),
        ),
        migrations.AddConstraint(
            model_name='fragranceperfumermodel',
            constraint=models.UniqueConstraint(fields=('fragrance', 'perfumer'), name='uq_fr_perfumer_link'),
        ),
        migrations.AddIndex(
            model_name='fragrancemodel',
            index=models.Index(fields=['brand', 'name'], name='idx_fragrance_brand_name'),
        ),
        migrations.AddIndex(
            model_name='fragrancemodel',
            index=models.Index(fields=['release_year'], name='idx_fragrance_year'),
        ),
        migrations.AddIndex(
            model_name='fragrancemodel',
            index=models.Index(fields=['likes_count'], name='idx_fragrance_likes'),
        ),
        migrations.AddIndex(
            model_name='fragrancemodel',
            index=models.Index(fields=['slug'], name='idx_fragrance_slug'),
        ),
        migrations.AddConstraint(
            model_name='fragrancemodel',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='uq_fragrance_brand_name'),
        ),
    ]
