# Generated by Django 5.2.9 on 2026-03-28 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fragrancenoteofficialmodel',
            options={'ordering': ['level', 'position', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='fragrancenoteofficialmodel',
            name='uq_fr_note_official',
        ),
        migrations.RemoveIndex(
            model_name='fragrancenoteofficialmodel',
            name='idx_fr_note_off_pos',
        ),
        migrations.AlterField(
            model_name='fragrancenoteofficialmodel',
            name='fragrance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_note_links', to='fragrance.fragrancemodel'),
        ),
        migrations.AddIndex(
            model_name='fragrancenoteofficialmodel',
            index=models.Index(fields=['fragrance', 'level', 'position'], name='idx_fr_note_off_lvl_pos'),
        ),
        migrations.AddConstraint(
            model_name='fragrancenoteofficialmodel',
            constraint=models.UniqueConstraint(fields=('fragrance', 'note', 'level'), name='uq_fr_note_official_per_level'),
        ),
    ]
