# Generated by Django 5.2.13 on 2026-06-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrance', '0002_alter_fragrancenoteofficialmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragrancenoteofficialmodel',
            name='level',
            field=models.CharField(choices=[('top', 'Р’РµСЂС…РЅС– РЅРѕС‚Рё'), ('heart', 'РќРѕС‚Рё СЃРµСЂС†СЏ'), ('base', 'Р‘Р°Р·РѕРІС– РЅРѕС‚Рё')], default='top', max_length=20),
        ),
    ]
