# Generated by Django 5.2.15 on 2026-06-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrance', '0004_fix_ambiguous_fragrance_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fragrancemodel',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perfumermodel',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
