# Generated by Django 5.2.4 on 2025-07-30 15:09

import core.common_services.file_service
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfumePhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('full', 'Full Bottle'), ('bottom', 'Bottom'), ('sprayer', 'Sprayer'), ('laser', 'Laser Code'), ('collage', 'Collage')], max_length=20)),
                ('image', models.ImageField(upload_to=core.common_services.file_service.upload_perfume_photo)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'perfume_photo',
                'unique_together': {('content_type', 'object_id', 'type')},
            },
        ),
    ]
