# Generated by Django 5.2.4 on 2025-08-01 09:38

import core.common_services.file_service
import core.validators.file_extention_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfumephotomodel',
            name='image',
            field=models.ImageField(upload_to=core.common_services.file_service.upload_perfume_photo, validators=[core.validators.file_extention_validator.validate_image_extension]),
        ),
    ]
