# Generated by Django 5.2.6 on 2025-09-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('photos', '0002_alter_perfumephotomodel_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='perfumephotomodel',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='perfumephotomodel',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'type'), name='uniq_photo_per_object_type'),
        ),
    ]
