# Generated by Django 5.2.9 on 2026-02-15 09:00

import core.common_services.file_service
import core.validators.file_extention_validator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('photos', '0003_alter_perfumephotomodel_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectCoverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(unique=True)),
                ('image', models.ImageField(upload_to=core.common_services.file_service.upload_object_cover, validators=[core.validators.file_extention_validator.validate_image_extension])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'object_cover',
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='uniq_cover_per_object')],
            },
        ),
        migrations.CreateModel(
            name='ObjectPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to=core.common_services.file_service.upload_object_photo, validators=[core.validators.file_extention_validator.validate_image_extension])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'object_photo',
                'ordering': ('position', 'id'),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='idx_objphoto_obj')],
            },
        ),
    ]
