# Generated by Django 5.2.13 on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0004_objectcovermodel_objectphotomodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectcovermodel",
            name="object_id",
            field=models.PositiveIntegerField(),
        ),
    ]
