# Generated by Django 5.2.13 on 2026-05-25 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('photos', '0005_alter_objectcovermodel_object_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfumephotomodel',
            options={'ordering': ('type', 'id')},
        ),
        migrations.RemoveIndex(
            model_name='objectphotomodel',
            name='idx_objphoto_obj',
        ),
        migrations.AlterField(
            model_name='objectcovermodel',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='objectphotomodel',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='perfumephotomodel',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='objectcovermodel',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_objcover_obj'),
        ),
        migrations.AddIndex(
            model_name='objectphotomodel',
            index=models.Index(fields=['content_type', 'object_id', 'position'], name='idx_objphoto_obj_pos'),
        ),
        migrations.AddIndex(
            model_name='perfumephotomodel',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_perfphoto_obj'),
        ),
    ]
