# Generated by Django 5.2.13 on 2026-06-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_alter_perfumephotomodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfumephotomodel',
            name='type',
            field=models.CharField(choices=[('full', 'Р¤Р»Р°РєРѕРЅ Р·Р°РіР°Р»СЊРЅРёРј РїР»Р°РЅРѕРј'), ('bottom', 'Р”РЅРѕ С„Р»Р°РєРѕРЅР°'), ('sprayer', 'Р РѕР·РїРёР»СЋРІР°С‡'), ('laser', 'Р›Р°Р·РµСЂРЅРёР№ РєРѕРґ'), ('collage', 'РљРѕР»Р°Р¶')], max_length=20),
        ),
    ]
