# Generated by Django 5.2.13 on 2026-06-12 07:15

import apps.photos.paths
import apps.photos.storages
import core.validators.file_extention_validator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('photos', '0007_alter_perfumephotomodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectcovermodel',
            name='image',
            field=models.ImageField(upload_to=apps.photos.paths.upload_object_cover, validators=[core.validators.file_extention_validator.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='objectphotomodel',
            name='image',
            field=models.ImageField(upload_to=apps.photos.paths.upload_object_photo, validators=[core.validators.file_extention_validator.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='perfumephotomodel',
            name='image',
            field=models.ImageField(upload_to=apps.photos.paths.upload_typed_perfume_photo, validators=[core.validators.file_extention_validator.validate_image_extension]),
        ),
        migrations.CreateModel(
            name='PrivateObjectPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(storage=apps.photos.storages.PrivatePhotoStorage(), upload_to=apps.photos.paths.upload_private_object_photo, validators=[core.validators.file_extention_validator.validate_image_extension])),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'private_object_photo',
                'ordering': ('position', 'id'),
                'indexes': [models.Index(fields=['content_type', 'object_id', 'position'], name='idx_privatephoto_obj_pos')],
            },
        ),
    ]
