# Generated by Django 5.2.13 on 2026-06-12 07:29

import apps.photos.paths
import apps.photos.storages
import core.validators.file_extention_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_alter_objectcovermodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectcovermodel',
            name='image',
            field=models.ImageField(max_length=255, upload_to=apps.photos.paths.upload_object_cover, validators=[core.validators.file_extention_validator.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='objectphotomodel',
            name='image',
            field=models.ImageField(max_length=255, upload_to=apps.photos.paths.upload_object_photo, validators=[core.validators.file_extention_validator.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='perfumephotomodel',
            name='image',
            field=models.ImageField(max_length=255, upload_to=apps.photos.paths.upload_typed_perfume_photo, validators=[core.validators.file_extention_validator.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='privateobjectphotomodel',
            name='image',
            field=models.ImageField(max_length=255, storage=apps.photos.storages.PrivatePhotoStorage(), upload_to=apps.photos.paths.upload_private_object_photo, validators=[core.validators.file_extention_validator.validate_image_extension]),
        ),
    ]
