# Generated by Django 5.2.9 on 2026-02-15 17:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('topics_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'forum_section',
                'ordering': ('order', 'title'),
                'indexes': [models.Index(fields=['is_active', 'order'], name='idx_forum_section_active_order'), models.Index(fields=['slug'], name='idx_forum_section_slug')],
            },
        ),
        migrations.CreateModel(
            name='ForumTopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_topics', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='forum.forumsectionmodel')),
            ],
            options={
                'db_table': 'forum_topic',
                'ordering': ('-last_activity_at', '-created_at'),
                'indexes': [models.Index(fields=['section', '-last_activity_at'], name='idx_forum_topic_section_last'), models.Index(fields=['author', '-created_at'], name='idx_forum_topic_author_created'), models.Index(fields=['slug'], name='idx_forum_topic_slug'), models.Index(fields=['is_pinned', 'is_locked'], name='idx_forum_topic_pin_lock'), models.Index(fields=['likes_count', 'comments_count'], name='idx_forum_topic_pop')],
            },
        ),
    ]
