# Generated by Django 5.2.9 on 2026-02-21 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='forumtopicmodel',
            name='idx_forum_topic_section_last',
        ),
        migrations.AddIndex(
            model_name='forumtopicmodel',
            index=models.Index(fields=['section', '-created_at'], name='idx_ft_sec_created'),
        ),
    ]
