# Generated by Django 5.2.9 on 2026-02-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_commentmodel_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='likes_count',
        ),
    ]
