# Generated by Django 5.2.9 on 2026-02-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_commentmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
