# Generated by Django 5.2.13 on 2026-05-25 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_commentmodel_likes_count'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ('created_at', 'id')},
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AddIndex(
            model_name='commentmodel',
            index=models.Index(fields=['likes_count'], name='idx_comment_likes'),
        ),
        migrations.AddIndex(
            model_name='commentmodel',
            index=models.Index(fields=['is_deleted', 'created_at'], name='idx_comment_deleted_time'),
        ),
    ]
