# Generated by Django 5.2.15 on 2026-06-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_commentmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
    ]
