# Generated by Django 5.2.6 on 2025-09-07 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProposalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_id', models.PositiveIntegerField()),
                ('offer_all', models.BooleanField(default=False)),
                ('offered_list', models.JSONField(blank=True, default=list, help_text='РќР°РїСЂ.: [{"type":"wardrobe","id":123}]')),
                ('message', models.TextField(blank=True)),
                ('accepted_items', models.JSONField(blank=True, default=list, help_text='РџРѕРґРјРЅРѕР¶РµСЃС‚РІРѕ offered_list РїСЂРё РїСЂРёРЅСЏС‚РёРё')),
                ('decision_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=16)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_proposals_received', to=settings.AUTH_USER_MODEL)),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_proposals_sent', to=settings.AUTH_USER_MODEL)),
                ('requested_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'exchange_proposal',
                'indexes': [models.Index(fields=['owner', 'status', 'created_at'], name='idx_exch_owner_status'), models.Index(fields=['proposer', 'status', 'created_at'], name='idx_exch_proposer_status'), models.Index(fields=['requested_ct', 'requested_id'], name='idx_exch_requested_gfk')],
            },
        ),
    ]
