# Generated by Django 5.2.7 on 2025-12-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeproposalmodel',
            name='cash_delta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Р“СЂРѕС€РѕРІР° СЂС–Р·РЅРёС†СЏ РїСЂРё РѕР±РјС–РЅС– (СЏРєС‰Рѕ С…С‚РѕСЃСЊ РґРѕРїР»Р°С‡СѓС”)', max_digits=9, null=True),
        ),
    ]
