# Generated by Django 5.2.13 on 2026-04-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_exchangeproposalmodel_cash_delta'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exchangeproposalmodel',
            new_name='idx_exch_prop_status',
            old_name='idx_exch_proposer_status',
        ),
        migrations.RenameIndex(
            model_name='exchangeproposalmodel',
            new_name='idx_exch_req_gfk',
            old_name='idx_exch_requested_gfk',
        ),
        migrations.RemoveField(
            model_name='exchangeproposalmodel',
            name='cash_delta',
        ),
        migrations.RemoveField(
            model_name='exchangeproposalmodel',
            name='offered_list',
        ),
        migrations.AddField(
            model_name='exchangeproposalmodel',
            name='offered_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='exchangeproposalmodel',
            name='accepted_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
