# Generated by Django 5.2.13 on 2026-05-25 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('exchange', '0003_rename_idx_exch_proposer_status_idx_exch_prop_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exchangeproposalmodel',
            index=models.Index(fields=['status', 'created_at'], name='idx_exch_status_created'),
        ),
    ]
