# Generated by Django 5.2.13 on 2026-06-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_exchangeproposalmodel_idx_exch_status_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposalmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'РћС‡С–РєСѓС” РІС–РґРїРѕРІС–РґС–'), ('accepted', 'РџСЂРёР№РЅСЏС‚Рѕ'), ('rejected', 'Р’С–РґС…РёР»РµРЅРѕ'), ('canceled', 'РЎРєР°СЃРѕРІР°РЅРѕ')], default='pending', max_length=16),
        ),
    ]
