"""
Django settings for configs project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from .extra_conf import *


# SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
# AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']
# CACHES = {
#     'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}
# }




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

def _env_bool(name: str, default: bool = False) -> bool:
    return str(os.getenv(name, str(default))).strip().lower() in ("1", "true", "yes", "y")


def _env_list(name: str) -> list[str]:
    raw = os.getenv(name, "")
    return [x.strip() for x in raw.split(",") if x.strip()]


def _env_path(name: str, default: Path | str) -> Path:
    raw = os.getenv(name, "")
    path = Path(raw) if raw else Path(default)

    if not path.is_absolute():
        path = BASE_DIR / path

    return path.resolve()


ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS") or [
    "localhost",
    "127.0.0.1",
    "0.0.0.0",
    "app",
    "testserver",
]
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", not DEBUG)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

TRUSTED_PROXY_IPS = _env_list("TRUSTED_PROXY_IPS") or [
    "127.0.0.1/32",
    "172.16.0.0/12",
]

CORS_ALLOWED_ORIGINS = _env_list("CORS_ALLOWED_ORIGINS") or [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = _env_list("CSRF_TRUSTED_ORIGINS") or [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
FRONTEND_URL = os.environ["FRONTEND_URL"]
DEFAULT_FROM_EMAIL = os.environ["DEFAULT_FROM_EMAIL"]

AUTH_USER_MODEL = 'users.UserModel'

PRESENCE_ONLINE_TTL_SECONDS = 600

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt.token_blacklist',
    'django_celery_beat',
    'django_celery_results',
    'rest_framework',
    'django_filters',


    #my_apps
    'core',

    'apps.auth',
    'apps.users',

    'apps.social',
    'apps.notifications',
    'apps.activity',

    'apps.wardrobe',
    'apps.taste_profile',

    'apps.favorites',
    'apps.exchange',

    'apps.photos',

    'apps.forum',
    'apps.articles',
    'apps.comments',
    'apps.tags',
    'apps.likes',
    'apps.mentions',

    'apps.fragrance',
    'apps.fragrance_ugc',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'configs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR / 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'configs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('MYSQL_DATABASE'),
        'USER': os.environ.get('MYSQL_USER'),
        'PASSWORD': os.environ.get('MYSQL_PASSWORD'),
        'HOST': os.getenv('HOST', 'db'),
        'PORT': os.getenv('PORT', '3306'),
        'TEST': {
            'NAME': os.getenv('MYSQL_TEST_DATABASE', 'test_aromanavigator_demo'),
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'mailpit')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 1025))
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", False)
EMAIL_USE_SSL = _env_bool("EMAIL_USE_SSL", False)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    'Aroma Navigator Demo <demo@aromanavigator.local>',
)

SOCIAL_AUTO_ACTIVATE_FB = _env_bool("SOCIAL_AUTO_ACTIVATE_FB", False)
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID", "")


# РѕРїС†РёРѕРЅР°Р»СЊРЅРѕ: РІРµСЂСЃРёСЋ Graph API РјРѕР¶РЅРѕ РєРѕРЅС„РёРіСѓСЂРёСЂРѕРІР°С‚СЊ РёР· .env
FACEBOOK_API_VERSION = os.getenv("FACEBOOK_API_VERSION", "v17.0")


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = _env_path("STATIC_ROOT", BASE_DIR / "staticfiles")
MEDIA_ROOT = _env_path("MEDIA_ROOT", BASE_DIR / "storage")
MEDIA_URL = os.getenv("MEDIA_URL", "/userApi/media/")

# Public user-generated files are intentionally configurable separately from
# MEDIA_ROOT. Today they can point to the local media directory; later they can
# be moved to another mounted volume/object storage by env only.
PUBLIC_MEDIA_ROOT = _env_path("PUBLIC_MEDIA_ROOT", MEDIA_ROOT)
PUBLIC_MEDIA_STORAGE_BACKEND = os.getenv(
    "PUBLIC_MEDIA_STORAGE_BACKEND",
    "django.core.files.storage.FileSystemStorage",
)
PUBLIC_MEDIA_BASE_URL = os.getenv("PUBLIC_MEDIA_BASE_URL", MEDIA_URL)
PUBLIC_MEDIA_STORAGE_OPTIONS = {
    "location": str(PUBLIC_MEDIA_ROOT),
    "base_url": PUBLIC_MEDIA_BASE_URL,
}

# Private files must never be served by the public media route. Keep them in a
# separate root/backend and expose them only through permission-checked views.
PRIVATE_MEDIA_ROOT = _env_path("PRIVATE_MEDIA_ROOT", BASE_DIR / "private_storage")
PRIVATE_MEDIA_STORAGE_BACKEND = os.getenv(
    "PRIVATE_MEDIA_STORAGE_BACKEND",
    "django.core.files.storage.FileSystemStorage",
)
PRIVATE_MEDIA_STORAGE_OPTIONS = {
    "location": str(PRIVATE_MEDIA_ROOT),
    "base_url": None,
}
STORAGES = {
    "default": {
        "BACKEND": PUBLIC_MEDIA_STORAGE_BACKEND,
        "OPTIONS": PUBLIC_MEDIA_STORAGE_OPTIONS,
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
FRAGRANCE_DEFAULT_COVER_IMAGE = os.getenv(
    "FRAGRANCE_DEFAULT_COVER_IMAGE",
    "template_fragrance_img/default-fragrance.svg",
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
APPEND_SLASH = False
